name: ingest-release

on:
  repository_dispatch:
    types: [ingest-release]

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repo
        uses: actions/checkout@v4

      - name: Download release artifacts from source repo
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.SOURCE_REPO_TOKEN }} # PAT with repo:read on source repo
          repository: ${{ github.event.client_payload.source_repo }}
          run-id: ${{ github.event.client_payload.run_id }}
          name: ${{ github.event.client_payload.artifact }}
          path: dist

      - name: Stage assets into releases/${{ github.event.client_payload.version }}
        run: |
          set -euo pipefail
          VERSION="${{ github.event.client_payload.version }}"
          TARGET="releases/${VERSION}"

          rm -rf "${TARGET}"
          mkdir -p "${TARGET}"
          cp -r dist/* "${TARGET}/"

      - name: Commit and push
        run: |
          set -euo pipefail
          VERSION="${{ github.event.client_payload.version }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "feat: ingest release ${VERSION} assets"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
